name: Python Application

on:
  push:
    branches:
      - main
      - dev-branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        something:something
    - name: Install Dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip installr requirements.txt  

    - name: Run tests
      run: |
        source venv/bin/activat  
        echo "No tests defined yet."
        
    - name: Missing Step Command
